# Generated by Django 6.0.5 on 2026-06-16 05:24

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=thumbnails.fields.ImageField(blank=True, default=None, null=True, upload_to='recipes/'),
        ),
    ]
