# Generated by Django 6.0.5 on 2026-06-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
