# Generated by Django 6.0.5 on 2026-05-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=0),
        ),
    ]
