# Generated by Django 6.0.5 on 2026-07-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='method',
        ),
    ]
