# Generated by Django 6.0.5 on 2026-07-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_description_recipe_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('none', ''), ('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('cup', 'cup'), ('tbsp', 'tbsp'), ('tsp', 'tsp'), ('oz', 'oz'), ('lb', 'lb')], default='none', max_length=5),
        ),
    ]
