# Generated by Django 6.0.5 on 2026-08-22 01:10

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredient_quantity_alter_ingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        # migrations.CreateModel(
        #     'TagCategory',
        #     [('name', models.CharField(default="Dietary"))]
        # ),
        migrations.RunSQL("INSERT INTO recipes_tagcategory (name) values (('Dietary'))"),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=django_summernote.fields.SummernoteTextField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.tagcategory'),
            preserve_default=False,
        ),
    ]
